### ISSUE TITLE
Make a REPL

### ISSUE THREAD

**Issue by cedric-h** [cedric-h/spoodly#11]
I mention a command line interface in the README.
A REPL would be a good first step in this direction.

I can envision the REPL as a bin target for the interpreter library portion of the project, where it's outlined in the Cargo.toml like so:
```toml
[[bin]]
name = "repl"
path = "src/repl.rs"
```
Once this is in the Cargo.toml, you could run the repl like so
```
cargo run --bin repl
```
